# -*- coding: utf-8 -*-
"""CostumerPersonalityAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TIuodH3PC4XdRlW9ZYQO2jU6GhT5m1sG
"""

import pandas as pd
import requests
import io

url  ="https://raw.githubusercontent.com/shadowmoon697/customer_personality_analysis/main/marketing_campaign.csv"
download = requests.get(url).content
data = pd.read_csv(io.StringIO(download.decode('utf-8')))
df = data.copy()
print(df.shape)
df.head()

"""#ABOUT DATASET:
2240 rows 29 columns

"""